name: "Test"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
jobs:
  build:
    name: "Test"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"

      - uses: "graalvm/setup-graalvm@v1"
        with:
          java-version: "23"
          distribution: "graalvm-community"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: "gradle"

      - uses: "actions/cache@master"
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
          chmod +x gradlew
          ./gradlew clean test build